baseURL: 'https://ycriticalhistory.org/'
languageCode: en-us
title: Critical History Map
params:
  author: Critical History Map
  message: ''
  description: ''
  hideAutoMenu: false
menu:
  main:
    - name: External
      url: '#'
markup:
  defaultMarkdownHandler: goldmark
