baseURL: 'https://ycriticalhistory.org/'
languageCode: en-us
title: Yale Critical History Map
params:
  author: Yale Critical History Map
  message: ''
  description: ''
  hideAutoMenu: false
menu:
  main:
    - name: External
      url: '#'
markup:
  defaultMarkdownHandler: goldmark
