backend:
  name: git-gateway
  repo: collinbentley1/critical-history
  branch: react-refactor
publish_mode: editorial_workflow
media_folder: /map/public/images

collections:
  - name: locations
    label: Locations
    label_singular: Location
    folder: /map/src/locations
    format: json
    create: true
    slug: "{{simple}}"
    identifier_field: title
    fields: 
      - {label: "Location Name", name: "title", widget: "string"}
      - {label: "File Name", name: "simple", widget: "string"}
      - {label: "ID", name: "id", widget: "number", valueType: "int"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Image Alt", name: "image_alt", widget: "string", required: false}
      - {label: "Image Credit", name: "image_credit", widget: "string", required: false}
      - {label: "Status", name: "status", widget: "string", required: false}
      - {label: "Bearing", name: "bearing", widget: "number", valueType: "float", required: false}
      - {label: "Map Center: Long, Lat", name: "center", widget: "list", max: 2, min: 2, valueType: "float"}
      - {label: "Marker Location: Long, Lat", name: "marker", widget: "list", max: 2, min: 2, valueType: "float"}
      - {label: "Map Pitch", name: "pitch", widget: "number", valueType: "float", required: false}
      - {label: "Map Speed", name: "speed", widget: "number", valueType: "float", required: false}
      - {label: "Map Zoom", name: "zoom", widget: "number", valueType: "float", required: false}
      - {label: "Text", name: "text", widget: "markdown"}

#           - name: name
#             label: 'Name'
#             widget: string
#             required: true
#           - name: start_url
#             label: 'Start URL'
#             widget: string
#             default: '.'
#             required: true
#           - name: display
#             label: 'Display Type'
#             widget: string
#             default: 'standalone'
#             required: true
#           - name: theme_color
#             label: 'Theme Color'
#             widget: string
#             default: '#000000'
#             required: true
#           - name: background_color
#             label: 'Theme Color'
#             widget: string
#             default: '#FFFFFF'
#             required: true
#           - name: icons
#             widget: list
#             label: 'Icons'
#             allow_add: true
#             fields:
#               - widget: string
#                 name: src
#                 label: Source
#               - widget: string
#                 name: sizes
#                 label: 'Sizes'
#               - widget: string
#                 name: type
#                 label: 'Mime Type'